### ISSUE TITLE
Github unusable under ubuntu-touch

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/morph-browser#269] opened 2019-11-30 15:35 UTC
Hello.
It is as much a question as it is a statement : it is now almost impossible to use Github under morph-browser, so with Ubuntu phones. It becomes a big blockage point. Do you know the reasons for this ? Is it due to updates in Github,  ¨lacks¨ in morph-browser... ?
Thank you.

**Comment by balcy** [comment] 2019-11-30 15:37
unfortunately it is most likely due to an outdated chromium version, we currently try to find a way to build QtWebEngine 5.13 which updates chromium

**Comment by gbdomubpkm** [comment] 2019-11-30 15:48
Thank you for the clear answer.

**Comment by balcy** [comment] 2019-11-30 15:54
you're welcome ! More info is at https://github.com/ubports/morph-browser/issues/223

**Comment by Flaburgan** [comment] 2020-01-17 10:48
Yep, this can be closed as a duplicate of #223 IMO.

**Closed as completed** 2020-01-17 11:59 UTC
Labels: bug, duplicate
