### ISSUE TITLE
Camera unavailable for browser & webapps

### ISSUE THREAD

**Issue by resoli** [ubports/morph-browser#62] opened 2018-10-16 20:45 UTC
I'm on OTA5 stable, device krillin. Using Talk Application under nextcloud permission is asked for using microphone, but not camera. Similar behavior trying https://test.webrtc.org/

**Comment by mateosalta** [comment] 2018-10-29 13:28
confirmed, similar webapp for wire worked on vivid, does not display camera test on xenial

**Comment by MK1973** [comment] 2018-10-31 11:09
Also confirmed trying to use appear.in, Morph can't access the camera, audiomicro works 
device: N5
channel: devel, OTA 5

**Comment by wayneoutthere** [comment] 2018-11-01 01:28
confirmed on Fairphone2.  
OTA 5
devel

tried to use Hubl.in (there is/was a webapp for it) and it couldn't access cam

**Comment by Thanassi1** [comment] 2018-12-08 09:01
bei meinem OPO seit OTA5 bis 6 arbeit arbeitet der Kamera zugriff im Browser nicht ,nur der zugriff fürs Mikrofon funktioniert

**Comment by ghost** [comment] 2019-02-08 12:19
I think that the possibility to use UT in videochat is very important but I cannot see that there is any work to fix this bug.
I always used hubl.in for videochat with friends.
Without videochat UT is not ready for daily use.

**Comment by UniversalSuperBox** [comment] 2019-02-08 16:58
@Lars-Leatherbiker, there are 12 people watching this repository and 7 this issue. Every comment sends an e-mail to all of them. Please be kind and only submit comments if you have new information to add to the issue.

This issue is marked as "help wanted", meaning it is waiting for a contributor that is willing to find the root cause of the problem and fix it. It is an admission of "I'm not sure how to fix this yet, so the door is open for someone else!"

**Comment by balcy** [comment] 2019-02-09 10:27
That's right, on the other hand it can be helpful to see which of the issues affect more people / are more important (like the heat feature on launchpad)
What I've seen so far is that non-android devices should have no problem accessing the camera.
For android devices (depending on libhybris) most likely QtWebEngine needs to be patched.
I will write some more details (e.g. how it was handled in oxide) and questions later.
The main problem is, that QtWebEngine does not use QtMultimedia to access the camera, but rather uses Chromium directly.

**Comment by ghost** [comment] 2019-02-09 10:47
Thank you for you answer, balcy.
Now I can understand the problem why it takes so long to fix the problem.
I am thinking just out of the box because it is important that more people using UT.
Probably it is not an important issue in the community but for the daily-use user of a smartphone outside the UT community this function is essential. Cannot using Whatsapp and a videochat app are THE arguments van friends not using UT. 
The community have to think about THIS people to make UT GREATER.  It is already great !

**Comment by ghost** [comment] 2019-02-09 10:56
......I have an Auqaris E5, FHD10 and OPO. The camera do not work in all these devices.

**Comment by balcy** [comment] 2019-02-09 16:50
```
#include <QtCore/QCoreApplication>
#include <QtMultimedia/QCameraInfo>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QList<QCameraInfo> cameras = QCameraInfo::availableCameras();
    qInfo() << "Length is " << cameras.length();

    qInfo() << "first id: " << cameras[0].deviceName() << " first name: " << cameras[0].description();
    qInfo() << "second id: " << cameras[1].deviceName() << " second name: " << cameras[1].description();

    return 0;
}
// result:
Length is  2
first id:  "0"  first name:  "Camera 0 Back facing"
second id:  "1"  second name:  "Camera 1 Front facing"
```
Ok so as shown with that simple program, with QtMultimedia it is possible to access the cameras on the device (in this case Aquaris 4.5). I think this works because it was patched to use libhybris on our devices.
> Qt WebEngine does use Chromium for multimedia, not Qt Multimedia, and changing the backend would probably be a major undertake. [https://bugreports.qt.io/browse/QTBUG-63258](https://bugreports.qt.io/browse/QTBUG-63258)

> Android cameras aren't Video4Linux devices [https://t.me/ubports/81398](https://t.me/ubports/81398)

This is how chromium accesses the video devices on linux: https://github.com/chromium/chromium/blob/master/media/capture/video/linux/video_capture_device_factory_linux.cc

For Oxide a special compile flag ENABLE_HYBRIS_CAMERA was used to access the camera: https://github.com/ubports/oxide/blob/c05c51d79a4d4ab18740e6542ddff02becd9b49c/shared/browser/media/oxide_media_capture_devices_dispatcher.cc

My question is: Would it in theory be possible that an android camera could appear as e.g. /dev/video0 ?  
If not, I think the only way to get it work is to patch QtWebEngine / Chromium so it uses the hybris compatibility layer (or, alternatively QtMultimedia) instead of the Video4Linux.

**Comment by mateosalta** [comment] 2019-04-30 22:15
hm, this sounds inserting: https://bbs.archlinux.org/viewtopic.php?id=209121 They are talking about a way to have the phone recognized as a webcam - maybe there is a way to use this to loop back on same phone? or some kind of wrapper that maps it to v4l? (random research ~ https://android.googlesource.com/platform/hardware/ti/omap4-aah/+/c0612fd3788965de3bffe6669e33746a45221c09/camera/V4LCameraAdapter/V4LCameraAdapter.cpp) don't know, hope this gets ideas flowing

**Comment by gsantner** [comment] 2019-12-15 18:28
I also run into this. Wanted to use a HTML/JS based QR-Code Reader, but unfortunately camera was not available/detected/loading at all

**Comment by likeadragonmaid** [comment] 2021-01-04 18:07
Microphone is also unavailable in addition to camera.

Device: jasmine_sprout
Channel: devel

**Comment by mateosalta** [comment] 2021-01-05 02:12
> Microphone is also unavailable in addition to camera.
> 
> Device: jasmine_sprout
> Channel: devel

hi, microphone is a separate issue

**Comment by fredldotme** [comment] 2021-12-21 18:41
Using the v4l2loopback kernel module and my new opticd project it is possible to gain camera support in Morph and other V4L2 applications:

https://github.com/fredldotme/opticd

The goal is to have these things fixed for OTA-22:
- [x] Basic 720p at 24fps support
- [ ] System-wide permission prompts
- [ ] Properly rotated picture
- [x] Debian packaging for opticd
- [ ] Fix Lomiri/QtMir spawning a placeholder when starting opticd

**Comment by fredldotme** [comment] 2022-01-17 23:12
The plan has changed, opticd has been put on the shelf for now.
Instead I decided to patch QtWebEngine, the Merge Request is available here:

https://gitlab.com/ubports/core/packaging/qtwebengine/-/merge_requests/7

The change to enable OpenGL back into QtWebEngine as a prerequisite is here:

https://gitlab.com/ubports/core/hybris-support/lxc-android-config/-/merge_requests/58

**Comment by mariogrip** [comment] 2022-01-18 22:18
Merged

**Closed as completed by mariogrip** 2022-01-18 22:18 UTC
Labels: bug, help wanted
