### ISSUE TITLE
Desktop mode not respected on first launch

### ISSUE THREAD

**Issue by bhdouglass** [ubports/morph-browser#127] opened 2018-12-14 00:55 UTC
Steps to reproduce
1. Ceck the desktop mode checkbox in the settings
2. Close the browser from the app spread
3. Relaunch the browser & find the user agent (duck duck go will do this if you search for it)
4. Observe "Android" in the user agent

If you toggle desktop mode off then on and refresh the page you'll have the correct user agent (without Android in the string). This could possibly be related to https://github.com/ubports/morph-browser/issues/109

**Comment by balcy** [comment] 2018-12-14 15:51
would be interesting to know if it is solved by https://github.com/ubports/morph-browser/pull/120

**Comment by bhdouglass** [comment] 2018-12-14 17:37
Sounds like it might!

**Comment by UniversalSuperBox** [comment] 2018-12-18 20:24
Fixed by #120

**Closed as completed by UniversalSuperBox** 2018-12-18 20:24 UTC

**Comment by Ingo-FP-Angel** [comment] 2019-01-01 16:05
Device: FP2
Channel: RC
Version: 2018-W01

I cannot reproduce the issue, i.e. the fix works.

**Comment by advocatux** [comment] 2019-01-01 20:24
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works

**Comment by cibersheep** [comment] 2019-01-02 03:45
Device: cooler
Channel: RC
Version: 2018-W01

I can't reproduce this issue
