### ISSUE TITLE
Can't remove all text from search box. 

### ISSUE THREAD

**Issue by davidmattson1** [ubports/morph-browser#92] opened 2018-11-08 03:43 UTC
BUG-REPORT

Device: Nexus 5
Channel: Stable
Build: OTA-5
Steps to reproduce
Open Morph Browser
Go to Google.com
Search for 'Test' and search
Try to remove all the text from the search box to search again. (Backspace 4 times)
It shows Test in the search box again
Expected behavior
Allow me to remove all the text and leave it blank

Actual behavior
Deleting all the text makes it show Test again

Logfiles and additional information
Not sure that I can.

Note:  I original opened this under the main project but I'm guessing this should go here.

**Comment by balcy** [comment] 2018-11-08 16:11
it certainly has to to with the input method.
There is currently one workaround: If you turn off "Spell checking" and "Word suggestions" in System Settings -> Language and Text, this does not happen.
The input method seems not properly being reset when the last letter is deleted.
Another workaround: before removing the last letter, click into the field again twice, so that the letter is no longer underlined, and then delete it.
I'm not sure if we can solve this in morph properly, or if it is a problem of QtWebengine itself.
Maybe we can call Qt.inputMethod.reset() when the keyboard opens to get rid of the problem

**Comment by ruedigerkupper** [comment] 2018-11-09 14:52
Confirmed.

**Comment by balcy** [comment] 2018-11-10 13:50
the problem is even a bit worse: If you are in a textarea, and press `abc<Enter>` and then `<Backspace>` you end up with `aab`, if you delete that you get `abc` again, which will reappear if you delete it.

And I've seen cases that allow the deletion of the whole text, but one more press on backspace will make the last word reappear. Actually we had some of those problems with Oxide too...

There are more cases like this, so it would not be enough to reset the input method when you enter a field.

**Comment by balcy** [comment] 2018-11-12 22:06
for some reason the last remembered word is in some cases cached, where it should not be:
e.g.
for all examples only type the letters, not the < and > symbols!

---
* type `>abc<` to the duckduckgo input field (or any other), it is underlined.
* press backspace 3 times -> the input is empty
* press backspace again (in the empty field) -> nothing happens
-> OK
---
* type `>abc <` (space after the c) to the duckduckgo input field
* press backspace -> abc is underlined again
* press backspace 3 times -> the input is empty 
* press backspace again (in the empty field) -> abc (underlined) appears again
-> NOT OK
---
* type `>abc de <` (spaces after c and e) to the input field
* press backspace (de is underlined)
* press backspace 3 times (the word is now "ade" with "de" underlined)
* press backspace 3 times (the word is now "de" which is underlined)
-> NOT OK
---
Now the OSK works with:
- Ubuntu Toolkit
- Qt Quick Controls
- Kirigami
But not for QtWebEngine, so I think there must be a problem there...
@UniversalSuperBox do you know how we could escalate that to Qt ?
Or could there be a chance to patch the problem ourselves ? Maybe there is just a commit() or reset() of the input method missing or at the wrong place.

**Comment by UniversalSuperBox** [comment] 2018-11-12 22:07
It would probably be in [our keyboard](https://github.com/ubports/keyboard-component), in the autocorrect stuff. You remember correctly, this has been a problem since forever.

**Comment by balcy** [comment] 2018-11-12 22:13
but with autocorrect enabled in the TextField / TextArea here https://open-store.io/app/qqc2-gallery.ubad it works fine. (the same example)

**Comment by UniversalSuperBox** [comment] 2018-11-12 22:24
Right. And again, we had the same problem with Oxide. I'm not sure if it's Chromium or something above it, but you seem to be on the right track.

I've tried to file bugs with Qt before. They normally at least reply within a week. You may also want to hop onto IRC for QtWebEngine to ask about this.

**Comment by balcy** [comment] 2018-11-15 16:56
Is it possible to test morph with any other on screen keyboard as reference ?
What I've seen in the logs is, that every time a word is finished (e.g. after pressing space after the word) at the same time the word is no longer underlined, the following does appear in the log:
`Data set on unsupported clipboard mode. QMimeData object will be deleted.`
not sure if it is related. So the keyboard component might be the problem / part of the problem after all as you said...
I think in the short term I can only think of a workaround like "Qt.inputMethod.commit()" before each backspace key press. (You loose the text prediction until you start the next word)

**Comment by balcy** [comment] 2018-11-17 13:52
@oSoMoN you have much experience with Oxide and the webbrowser-app, right ? Would you think this is a QtWebEngine problem, or rather the ubuntu touch keyboard component ?

**Comment by oSoMoN** [comment] 2018-11-19 09:20
Hard to tell without looking into it further, it could very well be that the problem requires fixes in both QtWebEngine and the keyboard component. We were definitely seeing similar issues with oxide and webbrowser-app.

**Comment by cibersheep** [comment] 2018-11-19 21:09
@balcy is a little worse... as you can see in [this issue](https://github.com/ubports/system-settings/issues/76)
Adress bar bug is fixed but you cannot tap on some OK buttons because of the predictive text getting in the way

**Comment by balcy** [comment] 2018-11-25 14:03
there was a problem that the keyboard for special chars and numbers was reset to the letter view, that is fixed with https://github.com/ubports/morph-browser/pull/114

**Comment by balcy** [comment] 2018-11-28 17:41
@cibersheep can you give an example of the problem with the OK buttons?
Might the OK button be hidden because of https://github.com/ubports/morph-browser/issues/52 ?

**Comment by cibersheep** [comment] 2018-11-28 20:01
Hey! I don't have my devices with Xenial with me until tomorrow but:
 - I confirm that is not related with #52 
 - If you open Linphone or Gelek, havinng predictive text on:
   - On Linphone start typing a sip address (call button should go green) but it's not until you type a final space
   - On Gelek open a game and start a command, button should change color but it's not until typing an space

Does that help?

**Comment by cibersheep** [comment] 2018-11-28 20:16
Sorry, @balcy as Dalton points, I have mixed an error occurring with native apps... so forgive me

**Comment by balcy** [comment] 2018-11-28 21:15
that's alright, it sounded like sth. else in morph (text field) has a problem with the OK button.

**Closed as completed** 2018-12-26 21:39 UTC
Labels: bug
