### ISSUE TITLE
Sound of video keeps playing in new window after being closed

### ISSUE THREAD

**Issue by 10JML01** [ubports/morph-browser#143] opened 2019-01-27 16:55 UTC
- Device: BQ M10 FHD (frieza) & BQ E5 HD (vegetahd)
- Channel: RC
- OS build number: 2019-W04
- UBports Image part: 20190124-10599

Steps to reproduce:
Open the Morph Browser.
Open New Window or new Private Window.
Go to Youtube and play a video (or a playlist).
Close the window that's running Youtube.

Expected behavior:
The window closes and therefore the sound of the video should stop.

Actual behavior:
The window "closes", however the sound of the video can still be heard. If it is a playlist, then after the song it will even load the next one and play that one. The screen will still lock after the set time.
It will only stop if you close all Browser windows. When you reopen Morph Browser, it is still gone.

**Comment by hummlbach** [comment] 2019-01-27 22:23
@10JML01 the right place for your bug report is most likely: https://github.com/ubports/morph-browser/issues

**Comment by UniversalSuperBox** [comment] 2019-01-28 19:22
This issue has been transferred

**Comment by balcy** [comment] 2019-01-28 22:02
exactly that behavior did occur to me last saturday. I've a possible fix for it.

**Closed as completed** 2019-01-30 07:43 UTC
Labels: bug

**Comment by jezek** [comment] 2019-03-01 15:11
FP2 (2019-W09)
Trying to reproduce bug using steps in initial post. After tab close, sound stops playing as expected.

**Comment by mattbel10** [comment] 2019-03-01 19:38
I cannot reproduce the described issue, therefore it is fixed thanks to @balcy .

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by haeckle** [comment] 2019-03-01 22:33
Fixed on Nexus 4 with 2019-W09

**Comment by erik-kueng** [comment] 2019-03-02 10:10
FP2
2019-W09
could not reproduce this issue

**Comment by ziggutas** [comment] 2019-03-02 15:29
Nexus 7 flo 2019-W09
Could not reproduce the issue
