### ISSUE TITLE
Browser does not handle SSL certificate errors

### ISSUE THREAD

**Issue by joolz** [ubports/morph-browser#70] opened 2018-10-19 08:28 UTC
I have problems opening sites with a self signed ssl cert. I know I can get a cert but I don't need one, I'm the only user. I can fetch the https page with wget but Morph just gives me a blank page, no error message. The page opens correctly on chrome on a recent Android (after a certificate warning)

More people have this issue, see https://forums.ubports.com/topic/1830/morph-browser-on-ota-5-no-self-signed-certs

**Comment by mateosalta** [comment] 2018-10-19 13:25
there was a flag you could  use for your own app, ill have to see if that was only oxide.

**Comment by balcy** [comment] 2018-10-21 11:52
I'll send a PR for this soon

**Comment by UniversalSuperBox** [comment] 2018-11-01 19:47
Closed by #73

**Closed as completed by UniversalSuperBox** 2018-11-01 19:47 UTC

**Comment by ghost** [comment] 2018-11-27 01:59
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce with multiple test sites using self signed certs.
