### ISSUE TITLE
Private browsing is not private

### ISSUE THREAD

**Issue by cm-t** [ubports/morph-browser#237] opened 2019-10-15 09:45 UTC
Hi,

context: 
* candidate channel : **60**, 2019-W41/2, 20191011-18642
* **pro5**, international version, 32Go

I don't know if it's a regression or was already here, but the session seems not sandboxed in private windows

1. open browser
2. menu/new private window
3. search on google
4. close all window of the browser
5. Repeat all step, when you search (step 3-bis), you will have suggestion of the previous searchs (from a ended private session)

Edit: I thought it was confined to private browsing, but it seems not:

6. repeat all steps in a new **Not** private window, and at step 3-bis-bis you will be able to see the history suggestion of the private windows, it is shared.

**Please check this [comment](https://github.com/ubports/morph-browser/issues/237#issuecomment-542182608) for a step by by step with github account example)**

Private window:
![image](https://user-images.githubusercontent.com/2675615/66820900-cb0c3b80-ef41-11e9-9d69-f998a9e729e9.png)

Normal Window:
![image](https://user-images.githubusercontent.com/2675615/66821615-01968600-ef43-11e9-872a-122635bff50f.png)

**Comment by mymike00** [comment] 2019-10-15 10:39
what's the behavior of this on desktop another browser? I think google can track you even in private browsing with morph and, once it recognized you, it displays your specific suggestions...
IDK how you can avoid this (other than avoiding google ofc :smile:)

**Comment by cm-t** [comment] 2019-10-15 10:44
I agree that the test should be done a website that is known for that kind of tests, but on my firefow desktop, when try to reproduce the steps, i don't have this issue, so there is something that tells me something is not a feature but a bug in here (from the browser itself) ;)

**Comment by mymike00** [comment] 2019-10-15 11:55
Indeed firefox is well known to have solid anti-tracking features, so maybe it's not just a bug but a missing feature... anyway, I agree with you it'd be really cool to have this fixed!

**Comment by cm-t** [comment] 2019-10-15 12:16
Think from google point of view: if there is the smallest hint about having someone's session different, you wont expose the account and its data outside the 'official' session (while google could still log secretly those new datas and probably mark them as "possibly same person" or "is that person getting hacked?"). 

I trully think this is nothing to do with browser fingerprint from google.

The session and cookies seems to be not sandboxed, that's all.

You made me wanted to check further, so here we are:

0. open a normale window
1. copy  & paste this url: https://github.com/ubports/morph-browser/issues/237
2. make sure you are connected, if not, connect to your github account
3. open the sandiwh menu and check your account github profile avatar
4. open a private windows
5. copy the url from step 1
6. open the sandiwh menu and check your account github profile avatar

Expected step 6: not connected, sign in link instead

Screen shoot from this issue:
![image](https://user-images.githubusercontent.com/2675615/66830456-d10c1780-ef55-11e9-8452-7b5a67af3a10.png)


Same, but from the private window i've just opened :
![image](https://user-images.githubusercontent.com/2675615/66830497-e7b26e80-ef55-11e9-87b8-7e15bad9932d.png)


Expected result: 

![image](https://user-images.githubusercontent.com/2675615/66830449-cbaecd00-ef55-11e9-96ed-69ee6677de75.png)

**Comment by mymike00** [comment] 2019-10-15 12:27
Oh... that's a serious issue then!

**Comment by balcy** [comment] 2019-10-16 19:45
I think the cause is the following commit (came with "DomainSettings" / "DomainPermissions")
https://github.com/ubports/morph-browser/commit/5a65c89f3c3c9ac372e2016f7042cfa74c0d2598#diff-e2100084e31ab20d6ea7cd28e7875dd6
the property `incognito` is already defined in MorphWebView.qml (Morph/Web) https://github.com/ubports/morph-browser/commit/79e6b6638d97e78b3c828c01bd4911604b632039#diff-f88008971a9cf96598fe24671fe22d53
Unfortunately after creating the variable, the "webview.profile.offTheRecord" switch stays "off" even in incognito mode

**Comment by balcy** [comment] 2019-10-16 20:02
@UniversalSuperBox I think we should not release OTA11 with that problem

**Comment by balcy** [comment] 2019-10-16 21:27
there is another issue, which has probably there for a longer time:
A shared webcontext (profile) is used, and opening a new window changes it:
- normal window (offTheRecord is false)
- new private window (offTheRecord is true for all windows)
- new window (offTheRecord is false for all windows !)
probably it is better to use a profile (like a sandbox) only for that window.
Not sure if that can be solved that quickly.

**Comment by balcy** [comment] 2019-10-17 20:42
if you retest the described issues and they are gone, we can open a new issue for creating separate profiles, and close this one.

**Closed as completed** 2019-11-01 14:32 UTC
Labels: bug

**Comment by UniversalSuperBox** [comment] 2019-11-01 14:38
Note for QA: This is the test plan that I used

1. Open Morph-Browser. Navigate to http://www.whatarecookies.com/cookietest.asp. 
1. Refresh the page 3 times. Verify the page says, "you have visited this site 3 times."
1. Open a private window. Navigate to http://www.whatarecookies.com/cookietest.asp.
1. Verify the page says, "No existing cookie was found for this website - a new cookie was successfully created"
1. Refresh the page once. Verify it says "you have visited this page 1 times [sic]."
1. Return to the non-private window.
1. Refresh the non-private window. Verify it says, "you have visited this page 4 times."

This bug was reopened with a slightly different intent than it originally had, the bug behavior is slightly different than the OP.

OP behavior was private browsing activity affecting, and being affected by, the main browser window.

The behavior being tested for now is private browsing activity *becoming* the main browser window, all of it being deleted after the browsing session completed. So, the browsing is private, but so is your non-private browsing.

**Comment by cm-t** [comment] 2019-11-01 22:15
I can confirm that:

* open the [link](http://www.whatarecookies.com/cookietest.asp) in normal browsing windows
* says i've visited 1 time 
* open same link in private windows
* says i've visited 2 times
* getting back to normal windows
* refreshing the page
* says i've visited 3 times

*(lastest candidate with lastest browser version from ota and/or open store)*

**Comment by jonnius** [comment] 2020-03-17 12:00
I confirm that this is fixed on RC, FP2. Within a private session, the visit counter is increased, but after closing and reopening no cookie can be found. Also the counting is completely separate between normal and private mode.

**Comment by cibersheep** [comment] 2020-03-17 18:30
Tested on M10 even if main search engine is DuckDuckGo I searched: «!g test if private is private» then several combinations in address bar and opening Google first.
Fix seams to work on M10HD RC

**Comment by Bolly** [comment] 2020-03-18 10:57
Fix confirmation on RC

-  M10HD

**Comment by luksus42** [comment] 2020-03-18 18:38
Fix confirmed with E4.5 on RC.
