### ISSUE TITLE
Feature: Is not posible to close the current tab

### ISSUE THREAD

**Issue by j2g2rp** [ubports/morph-browser#50] opened 2018-10-13 10:24 UTC
In oxide when you made the gesture to show tabs you could close all tabs.

In morph there isn't buttons to close current tab. 
Not sure if this is intentional, feature or a bug.

**Comment by ruedigerkupper** [comment] 2018-10-17 19:22
Missing this, too. In order to close the current tab, you first have to switch to another tap, repeat the swipe guesture, then close it.
That's inconvenient, can't imagine this is by design?

**Comment by mihaelmilea** [comment] 2018-10-18 16:22
I put my device in landscape orientation and there I can close the first tab... Still, we need to be able to close the first tab from portrait orientation.

**Comment by mateosalta** [comment] 2018-11-07 03:12
I think the header may be overlapping the area, I wonder if some of the if logic for hiding the header was messed with. It should be possible to access again if we hide it on bottom gesture

**Comment by ruedigerkupper** [comment] 2018-11-09 14:54
The workaround (putting device in landscape mode) does not work for me on a Nexus 5.

**Comment by balcy** [comment] 2018-11-12 22:35
for my device (BQ Aquaris 4.5) landscape mode does not make a difference, too

**Closed as completed** 2018-12-29 02:12 UTC
Labels: enhancement

**Comment by Ingo-FP-Angel** [comment] 2019-01-01 15:34
Device: FP2
Channel: RC
Version: 2018-W01

I can close the current tab by tapping the 'x' next to the address bar. If that's how it's supposed to work I'd say the bug is fixed.

**Comment by 10JML01** [comment] 2019-01-01 16:50
Device: BQ E5HD and M10FHD
Channel: rc
Version: 2018-W01

The fix works. Now there is an 'X' next to the adress bar that closes the current tab.

**Comment by advocatux** [comment] 2019-01-01 19:20
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

Fix works.
