### ISSUE TITLE
WebRTC unmasks VPN revealing true IP

### ISSUE THREAD

**Issue by electricbrain-code** [ubports/morph-browser#521] opened 2021-11-12 18:14 UTC
Morph Browser's WebRTC unmasks VPN revealing true IP.
https://browserleaks.com/webrtc
Can WebRTC be disabled by the user?

**Comment by mateosalta** [comment] 2021-11-13 13:24
Possible duplicate of: https://github.com/ubports/morph-browser/issues/257

**Comment by electricbrain-code** [comment] 2021-11-13 18:20
Sorry, yes correct - this is a duplicate.

**Closed as completed** 2021-11-13 18:21 UTC
