### ISSUE TITLE
Media does not stop when a tab is closed

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/morph-browser#59] opened 2018-10-16 14:27 UTC
Moved from https://github.com/ubports/ubuntu-touch/issues/913

The browser continuous playing of a sound (f.e. Youtube audio) even the panel with such multimedia has been closed. It is necessary to close the browser completely to stop the playing

- Device: BQ M10 Aquaris FHD

### Expected behavior
I appreciate that murph keeps playing e.g. IPTV even I switch the browser to another tab opened, but the browser must stop playing audio when I close the tab with e.g. IPTV, Youtube etc...

### Actual behavior
The browser continuous playing of a sound (f.e. Youtube audio) even the panel with such multimedia has been closed. It is necessary to close the browser completely to stop the playing

**Comment by balcy** [comment] 2018-10-17 10:30
what I can say is that in BrowserTab.qml there is a problem:

```    function unload() {
        if (webview) {
            initialUrl = webview.url
            initialTitle = webview.title
            initialIcon = webview.icon
restoreState = webview.currentState
            //restoreType = Oxide.WebView.RestoreCurrentS$
            webview.destroy()
            gc()
        }
    }
```
the "restoreState =..." cannot be executed, because the webview does not have this property. 
BUT: If the unload function does work after removing the line, at least on Aquaris 4.5 the tab is unloaded not only if you close it, but on tab switch as well. So the music would stop in this case

**Comment by balcy** [comment] 2018-10-17 10:35
```
file:///usr/share/morph-browser/webbrowser/BrowserTab.qml:125: Error: Cannot assign [undefined] to QString

```

**Comment by balcy** [comment] 2018-11-08 18:29
I think because of memory problems on low spec devices (https://github.com/ubports/morph-browser/issues/93) we should properly unload the tab, so no background music from other tabs

**Comment by balcy** [comment] 2018-11-11 20:54
https://github.com/ubports/morph-browser/pull/96

**Closed as completed** 2018-11-12 19:05 UTC
Labels: bug

**Comment by ghost** [comment] 2018-11-27 01:46
device:Nexus 5
channel: RC 2018-W48
issue solved. Unable to reproduce

**Comment by tjrhodes** [comment] 2018-11-27 17:20
Device: FP2
System Build: 2018-W48

issue solved, unable to reproduce.

BUT that's because the background tabs are unloaded, which is another issue. It's currently impossible to keep playing audio in one tab and browse in another.

**Comment by MEstner** [comment] 2018-12-02 12:46
fixed in 2018-w48 m10 fhd
Could not reproduce issue.
