### ISSUE TITLE
whith multiple tabs open, it's impossible to close currently focused tab

### ISSUE THREAD

**Issue by matv1** [ubports/morph-browser#68] opened 2018-10-18 10:35 UTC
Having openend multiple browser tabs, then swiping up, there is no way to close the currently focused tab in portait mode. The focussed tab does not have an x to kill it. It did in the old Oxide browser.

(in landscape mode however all the open tabs do have x's)

**Comment by mihaelmilea** [comment] 2018-10-18 16:23
Maybe duplicate of: https://github.com/ubports/morph-browser/issues/50 ?

**Comment by matv1** [comment] 2018-10-18 20:36
you are right. It is the same issue. I overlooked it because it was labeled as a feature request, and I consider this a bug. I will close this one nonetheless. Thnks.

**Closed as completed** 2018-10-18 20:36 UTC
Labels: duplicate
