### ISSUE TITLE
Microphone access not working

### ISSUE THREAD

**Issue by Flaburgan** [ubports/morph-browser#399] opened 2020-10-15 16:31 UTC
To be able to send vocal messages with Axolotl, we need to access the microphone. It looks like even with OTA-13 and the QtWebEngine upgrade, the microphone isn't working. When going to a website like https://framatalk.org/test, the access to the microphone is asked, but even after saying Yes in the UT popup to give permission, the website can't access the microphone.

Tested on a Fairphone 2 Halium 5.1 port, running the last devel build.
Same problem with my Pinephone last devel.

**Comment by Flaburgan** [comment] 2020-10-15 16:42
@Flohack74 I heard that with your 6P such feature is working, can you please try the link above and confirm?

**Comment by Flohack74** [comment] 2020-10-15 17:07
Yes it works for me, trust prompt appears, and recording seems to work as the round circle pulses when i speak.

**Comment by nanu-c** [comment] 2020-10-15 18:36
Broken at least on  fp2, volla phone and pro 5.

**Comment by nanu-c** [comment] 2020-10-15 18:55
js log, tells when i request permission and allow them with `grantFeaturePermission(securityOrigin, feature, true);` And also happens with plain webengineview.

```
shm_open() failed: Permission denied
```

**Comment by rubencarneiro** [comment] 2020-11-15 23:13
Also wont work on volla phone and nexus 5. Neither microphone or camera access. Tried using on jitsy

**Comment by Danfro** [comment] 2020-12-10 17:00
On my Xperia X 32 bit devel using morph I have just tested a web based video conference system [senfcall.de](https://senfcall.de) (an instance of [BigBlueButton TM](https://bigbluebutton.org/)):
- watching video output from desktop -> works only one way
- watching a shared screen from dektop -> works only one way
- listening to speech from desktop and talking on the phone -> working both ways

I was asked if I want to give microphone permissions. Confirmed that. Yeah, works!

Also tried a jitsi.meet conference. Works too.

**Comment by Danfro** [comment] 2020-12-19 11:47
Just tested on my E5 (devel, Qt5.12 test environment enabled).

Microphone does NOT work. Only listening to callers. So this really seems to be device dependend. Xperia X seems to be on the lucky side. ;-) We need to find out what does make the difference.

**Comment by luksus42** [comment] 2021-02-21 20:37
Btw. microphone access works for me now in Morph on Halium9 FP3.
I can record and playback audio on this site: https://online-voice-recorder.com/

**Comment by stanwood77** [comment] 2021-04-17 20:31
I confirm the issue.

Device: Xiaomi Redmi Note 7 Lavender
Channel: OTA-16 Stable
Used website: https://online-voice-recorder.com
Browser: Morph Browser
Microphone access: Allowed

Website replied that Microphone access has been denied. (See screenshots)

Remark: App "Music Recognition" does not start recording. https://github.com/luksus42/soundrecog/issues/7

Btw, no problem with Nexus 5 + Vollaphone. Only my Redmi Note 7 is affected by this issue.

Thank you beforehand. Regards, Steve

![photo_2021-04-17_22-13-07](https://user-images.githubusercontent.com/62994815/115125976-10447a00-9fcc-11eb-917d-46ca2a91ef6c.jpg)

![photo2_2021-04-17_22-13-07](https://user-images.githubusercontent.com/62994815/115125986-1c303c00-9fcc-11eb-958e-de672ab571ae.jpg)

**Comment by luksus42** [comment] 2021-07-07 21:57
uh, I thought we would get a fix for this soon :-(

**Comment by stanwood77** [comment] 2021-07-08 22:14
@UniversalSuperBox Ok... So will this issue be reported in OTA-19?

**Comment by UniversalSuperBox** [comment] 2021-07-09 00:38
@stanwood77, possibly, if review of any contributions completes and works correctly for your device. I'm not sure if the linked pull request will fix your device exactly, since Ratchanan doesn't have a Redmi Note 7. But you could certainly test it out to help us test it, that will improve the likelihood that it gets merged in OTA-19.

**Comment by Flaburgan** [comment] 2021-09-26 21:02
Hm, I just tried and at least with the PinePhone running last devel (692) this isn't fixed. Tried on https://online-voice-recorder.com/
@mariogrip what commit is supposed to solve that issue?

**Comment by luksus42** [comment] 2021-11-16 08:36
Trust prompt for microphone access in morph browser ( or MorphWebView) does not appear on:
- BQ e4.5 devel (after factory reset)
- Fairphone 2 halium-devel (after factory reset)
- Fairphone 2 devel (after factory reset)
- Fairphone 3 devel (Halium 10)
- Lenovo X605 devel (Halium 9)

**Comment by Flaburgan** [comment] 2021-11-16 09:05
@luksus42 can you please provide a screenshot of "trust-prompt", because now I'm confused about what we are talking about. As said when I created that issue, I do have a prompt asking to access mic on FP2, but accepting it doesn't grant the permission.

**Comment by luksus42** [comment] 2021-11-16 10:38
So this is the one of the browser:
![browser:prompt](https://user-images.githubusercontent.com/62994815/115125976-10447a00-9fcc-11eb-917d-46ca2a91ef6c.jpg)

But we also need the one of the system, to get access to the microphone:
![screenshot20211116_113424154](https://user-images.githubusercontent.com/6659488/141970021-c7d057e4-d50f-41a8-86cc-2245966181a5.png)

**Comment by Danfro** [comment] 2021-11-16 14:49
Trust prompts are currently broken. Please see [https://github.com/ubports/ubuntu-touch/issues/1814](https://github.com/ubports/ubuntu-touch/issues/1814).

**Comment by Flohack74** [comment] 2021-11-16 18:20
@danfro well actually they should not be broken in RC and devel :)

**Comment by Danfro** [comment] 2021-11-16 18:54
Darn, sure. :-D You are right. It was broken but should not be broken anymore. 

(IF it is still broken, then please comment on the OTA20 board.)

--

**Comment by stekalb** [comment] 2021-11-16 19:07
so to conclude:
- microphone trust prompt works for most apps, e.g. recorder app
- microphone trust prompt doesn't work for morph

**Comment by Flohack74** [comment] 2021-11-16 19:11
So I reopened this issue and moved it OTA-21... Sorry to say but this does not work at all it seems @peat-psuwit

**Comment by peat-psuwit** [comment] 2021-11-17 09:14
Well, no wonder why it doesn't work: the build for the merge commit fails. 🤦

![ภาพหน้าจอจากเมื่อ 2021-11-17 16-13-21](https://user-images.githubusercontent.com/6771175/142171449-5bdca0c3-bc40-4cd8-9eb7-26a43eba464d.png)

So, TODO: kick a retry build after OTA-20 is released.

**Comment by Flohack74** [comment] 2021-11-18 11:56
Oh thx for looking. Doh! Will do

**Comment by peat-psuwit** [comment] 2021-11-22 15:31
With the rebuild triggered, this issue should be fixed in devel image now.

Note for QA: for Morph Browser, there will be 2 kinds of prompts, showing below:

|  Morph's own prompt  |  System's prompt |
|------------------------------|-------------------------|
| ![screenshot20211122_222225474](https://user-images.githubusercontent.com/6771175/142888160-b8c4cf04-21cd-4156-bf55-fdc64020f5c5.png) | ![screenshot20211122_222247748](https://user-images.githubusercontent.com/6771175/142888221-bb9afed0-a284-4b52-88f4-e18871c2e266.png) |

The first prompt will always appear, while the second prompt will appear the first time Morph uses the microphone. It's this second prompt which is broken, not the first one.

On Pinephone, the second prompt has always been not working, and Morph should always be allowed accessing the mic. If that's not the case, please file a separated issue.

**Closed as completed by peat-psuwit** 2021-11-22 15:31 UTC
Labels: bug

**Comment by luksus42** [comment] 2021-11-23 15:16
So this seems to work now. (FP3, halium 10 devel, 2021-11-21)

I have had on issue though, but I cannot reproduce it:
- I updated the device with OTA
- then it worked: the test-recording app which displayed the system prompt, was also able to record something
- then I did nothing with the device for hours, I got an alarm in between
- then I started the test-app again, which was not able to record anymore
- the mic-rights in the systemsettings app-rights where greyed out and showd "0/0" (like camera-rights)
- after a reboot everything worked again

**Comment by Fuseteam** [comment] 2021-11-25 10:21
Appears to work, tests so far no longer complains about mic access

**Comment by lduboeuf** [comment] 2021-12-15 11:21
Works well on XperiaX, with that website: https://fr.mictests.com/
thanks for that fix
